### PR TITLE
First cut at expiring passwords

### PR DESCRIPTION
**Pull request by MrTact**
Move password expiry option to the extension options page
Add "In-memory expire" option
Add field to the options page to specify expiration time (minutes)

### CODE REVIEW

**Comment by MrTact** [comment]
Please note that this pull request is for code review, feedback and testing purposes. It is almost certainly not ready for prime time.

**Comment by heavensrevenge** [comment]
Interesting feature, I've been looking at it and playing around with it, as I have been wanting to move that option out of the popup or possibly have it in both places for the time being.

**Comment by heavensrevenge** [comment]
One thing I was never able to do was set ```"persistent": false``` since it'll always destroy the password variable state from the background/event page, and I really wanted to avoid ever touching the disk if the store_location was just "memory" aka I tried avoiding it from touching the disk even if it was encrypted.
Any ideas on how to maintain state beyond saving to persistent localStorage?

**Comment by heavensrevenge** [comment]
So any feedback or suggestions on the extension persistence problem?

**Comment by MrTact** [comment]
Sorry, I have been traveling and I have not had a chance to even look into
it. I will say off the bat that it's not an area in which I have a lot of
expertise. But I will give it a look once I get home next week and see
whether anything comes to mind.

**Comment by MrTact** [comment]
Hey, I finally got a chance to look at this. As far as I can tell, the only
straightforward way to store stuff in session memory is if the background
page is not set to "persistent: false." Regrettably, it seems you can only
access the alarms API if you are using an event page, so it looks like "in
memory: expire" is dead.

Using a native client module is the only way I can see at the moment that
it might work, but I know nothing about that.

TK

**Comment by heavensrevenge** [comment]
@MrTact I have a version I'll be committing that has a complete implementation of your expiration feature :smile:

**Comment by heavensrevenge** [comment]
@MrTact I updated the chrome web store version to 0.8.2 with expiring passwords so give it a try and see what you think

**Comment by MrTact** [comment]
Neat! I'm very curious to see how you implemented the timer without using
an event page!

**Pull request merged**
