### PR TITLE
Firefox port

### PR DESCRIPTION
**Pull request by dolohow**
I started working on this port.  Please let me know if you are going to upload this extension to mozilla addons.  If not I can try to do it.

Sync is probably not working due to some bugs in Firefox implementation of syncing.

Issue #142 #146

### CODE REVIEW

**Comment by dolohow** [comment]
Any plans on mergin this work?

**Comment by heavensrevenge** [comment]
Hey, I can't exactly merge it in directly since Firefox's implementation requires an unsupported "app" key in the manifest.json file ATM so it would need its own repo like firefox-passwordmaker.

**Comment by dolohow** [comment]
Yes, but this will be ignored by chrome, right?   And it's only necessary for cloud sync.

**Comment by heavensrevenge** [comment]
Ill have to try it, I know it complained and mentioned it but I'll have to
try it in a clean install to make sure.

Also even though it's not an important factor but kind of pride without the
clipboardWrite permission as it stands Chrome mentions 0 permissions needed
in viewing extended details.

I do have crazy working hours ATM but I will look into it, I always prefer
to be quick to communicate.

**Comment by gr-g** [comment]
I see there is now a different firefox port uploaded on addons.firefox.org:
https://addons.mozilla.org/en-US/firefox/addon/firefox-passwordmaker-pro/
Github repo: https://github.com/yb171/chrome-passwordmaker/tree/firefox

Can you tell if this is something you know about, and if you generally endorse it?

It would also be nice to know how this compares with dolohow's port...

Thanks!

**Comment by heavensrevenge** [comment]
I didn't know about it and can't endorse it yet.  I want to make a Firefox repo port here since I don't think it should be integrated into the WebKit based browser repo that includes Chrome, Opera and Vivaldi.
I did install it and saw the timed password expiry doesn't work but most of it does which is good.

@dolohow have any thoughts on it?

**Comment by dolohow** [comment]
Firefox and Chrome can use the same codebase, because their API's are very much the same.  I implemented few workarounds in order to support sync, but that does not break chrome extension at all.

Having two repos for firefox and chrome will be a nightmare.

**Comment by heavensrevenge** [comment]
Well @dolohow we have 3 repos as it is, they are quite separate.  The only reason why I even suggest is because I really love the no special permissions at all required for the Chrome extension yet Firefox needs "clipboardRead", "clipboardWrite" added to the manifest.json in order to function which messes that up.
I also found the "Per Session, Expire" time option to not function in FF but I don't know how to debug that yet in FF to find the cause which would probably force the code to diverge more but maybe not, it needs investigation.
And I would be cool with giving you and the other guy FF repo permissions to work on it together if you were interested, Since honestly a FF port is kind of needed, and I'd rather a sanctioned & official one I can vouch for and advertise/direct to.

**Comment by dolohow** [comment]
You could have separate manifests just for this purpose.  In future, Chrome might adjust its permission model to be compatible with `WebExtensions`.  And in fact this extension writes to clipboard, it would be nice to inform Chrome users about it anyway.

BTW only "clipboardWrite" is used in my patches.

**Comment by heavensrevenge** [comment]
Is the getBytesInUse function the only needed change for your port to work for you? Since I see lots of chrome. to browser. api call changes and turning many callbacks into promises https://github.com/passwordmaker/chrome-passwordmaker/compare/master...yb171:firefox sans maintenance I have queued up in my local branch.

**Comment by dolohow** [comment]
> Is the getBytesInUse function the only needed change for your port to work for you?

s/chrome/browser does not make sense, because it is an alias.  Not sure about expire functionality on Firefox, I can dig into that.  But yes, this is fully functional port.

**Comment by dolohow** [comment]
Any update in regards to merging this work?

**Comment by heavensrevenge** [comment]
Well @dolohow I'm undecided based on FF still working on their WebExtension implementation to just merge, I'm still leaning towards a separate repo for the FF port. It isn't far off but they need to mature a bit more.
Also, have you found out why the timer expiry function isn't working in FF?

**Comment by miquelfire** [comment]
FYI, Firefox updated to the version that only supports the web extension extensions yesterday, so only ESR Firefox users can use the original version now.

**Comment by heavensrevenge** [comment]
Hey @miquelfire haven't heard from you in a while, so @dolohow is your version still working? Or will you need to change the `chrome.` to `browser.` API calls and use promises for most `browser.` API  calls?

**Comment by dolohow** [comment]
>  Also, have you found out why the timer expiry function isn't working in FF?

I will start working on it soon as you merge this work :) as it is not my primary interest/

> Hey @miquelfire haven't heard from you in a while, so @dolohow is your version still working? Or will you need to change the chrome. to browser. API calls and use promises for most browser. API calls?

Yes, it does work.

I added two new commits for better compatibility between Chrome and Firefox.  There is no need for two repos, everything works fine both in Firefox and Chrome, later in Edge.

**Comment by dolohow** [comment]
I can't find the root cause of alarms not being fired.  I eliminated all runtime errors from background page.  The API is compatible, no idea what is going on.  Maybe Firefox bug?  No idea now.

**Comment by heavensrevenge** [comment]
Hey @dolohow could you instead of adding the whole polyfill for `getBytesInUse` just add the logic of distinguishing between chrome & FF and put in https://github.com/passwordmaker/chrome-passwordmaker/pull/163/commits/fec200015a98156829c9e9ba80fdb805d2f0b8b9#diff-7af57b96a25a85839e1728a0587c2adfR35 where the 2 places `getBytesInUse` is used?
I am wanting to merge this in soon though because I like it so far.

**Comment by dolohow** [comment]
> Hey @dolohow could you instead of adding the whole polyfill for getBytesInUse just add the logic of distinguishing between chrome & FF and put in fec2000#diff-7af57b96a25a85839e1728a0587c2adfR35 where the 2 places getBytesInUse is used? But you may need to do a Promise based return in FF for their API implementation.

I can, but Firefox sooner or later add support for `getBytesInUse` and all you gotta do is to remove this polyfill.  If I am gonna patch the specific place the logic will be more complicated.  Polyfill is simple and elegant.  This is standard way of dealing with browser API differences.

>  In FF in order to test if it functions just play with deleting your sync data and saving it with a password and see if profiles appear during a synchronization.

I tested sync in FF and it works flawlessly.  I tried deleting profile multiple times, removing extension, adding back again and its working.

**Comment by dolohow** [comment]
Any update?

**Comment by dolohow** [comment]
Do you plan merging those changes?  Otherwise I will create my own fork and put extension to mozilla addons.  This is not something I would like to do.

**Comment by heavensrevenge** [comment]
Thing is I'd still rather there be a FF "port" versus in the main repo.  Problem is i dont know how to debug under FF yet but if I did I'd be more confident taking this and testing in FF myself.  So being the FF maintainer of a "blessed" port is up for grabs.
At least for the time being, after FF and Edge stabilize and complete their webextension implementation this can be more clear of what is what, it took about 2 years for Chrome/Opera to not suck after they started using Blink.

**Comment by ThiefMaster** [comment]
Debugging in FF is quite easy: Go to `about:debugging` and enable add-on debugging. Then click the debug button next to the addon below.

**Comment by heavensrevenge** [comment]
I'll be on a Christmas vacation of sorts in a day or 2, I'll try to get FF debugging down pact after I finally get some time to myself then maybe I'll just officially release for FF. Thanks @ThiefMaster

**Comment by dolohow** [comment]
How's going?

**Comment by dolohow** [comment]
Any update?

**Comment by gwillegers** [comment]
I would love to see a FF port of this extension. I am still using the original PasswordMaker, so at the moment I am stuck at FF version 56 (since starting with version 57 XUL extensions are no longer supported).

**Comment by dolohow** [comment]
https://addons.mozilla.org/en-US/firefox/addon/passwordmaker-pro-firefox/

**Comment by gwillegers** [comment]
Thank you, I missed that one. What is the relationship with [https://addons.mozilla.org/en-US/firefox/addon/firefox-passwordmaker-pro/](https://addons.mozilla.org/en-US/firefox/addon/firefox-passwordmaker-pro/)?

**Comment by heavensrevenge** [comment]
They are both based off this code which I haven't ported to FF yet, Peters code has far more alteration an has done the switch to using chrome.storage.local vs localStorage which I've been working on but chrome can't use promise based code and can only use old school callback style calls for it's API so I'd sadly need to change more than the manifest.json and swap all chrome. calls to browser. calls for to be a proper webextension to future proof this more so I'd really need to make a split repo.  I really would be ok with grabbing Peter's repo and giving you FF guys access to it to work on together unless I have time to Port it myself.  I really do want an official port for FF vs just others repackaging this plus some tweaks but I'm glad there's 2 there for now for users to use for the time being. I have 6 days off so hopefully I'll get to some porting and merging of both your work with my more recent code for the webextension repo.

**Comment by heavensrevenge** [comment]
Just remember this as well, I support Opera and Vivaldi not just chrome, so it's not just chrome vs webextension.  Eventually I'll try to sneak Edge in there as well since it almost already works in my local code now. But ff is def a high priority for me to get working and keep current and maintained.

**Comment by heavensrevenge** [comment]
Hey @dolohow are you still around these days?  I've changed from localStorage to chrome.storage(local/session) In my master branch but I've messed up sync, would you be able to help me with it?

**Comment by heavensrevenge** [comment]
As of 0.10.0 we are completely source compatible with FF so a port isn't really required anymore.

**Pull request closed without merging**
